-- ========================================
-- COMPLETE CUSTOMER DATA IMPORT
-- ========================================

-- Import ALL Garment Types (54 items)
INSERT INTO garment_type (code, name, category, icon, is_common, is_active, base_price_cents, pricing_model, unit_type, description, is_material) VALUES
('B_TON_FIBRE_36_BLANC', 'Bâton fibre 36" Blanc', 'curtains', '🪟', true, true, 200, 'fixed', 'piece', 'Bâton fibre 36" Blanc', false),
('B_TON_FIBRE_48_BLANC', 'Bâton fibre 48" Blanc', 'curtains', '🪟', true, true, 0, 'fixed', 'piece', 'Bâton fibre 48" Blanc', false),
('B_TON_FIBRE_60_BLANC', 'Bâton fibre 60" Blanc', 'curtains', '🪟', true, true, 0, 'fixed', 'piece', 'Bâton fibre 60" Blanc', false),
('B_TON_FIBRE_96_BLANC', 'Bâton fibre 96'''' Blanc', 'curtains', '🪟', true, true, 0, 'fixed', 'piece', 'Bâton fibre 96'''' Blanc', false),
('B_TON_TRANSPARENT_30', 'Bâton transparent 30"', 'curtains', '🪟', true, true, 0, 'fixed', 'piece', 'Bâton transparent 30"', false),
('CHARIOT_MAITRE', 'Chariot Maitre', 'curtains', '🪟', true, true, 0, 'fixed', 'piece', 'Chariot Maitre', false),
('CHARIOT_RIPPLEFOLD_BLANC_60', 'Chariot Ripplefold Blanc 60%', 'curtains', '🪟', true, true, 80, 'fixed', 'piece', 'Chariot Ripplefold Blanc 60%', false),
('CONFECTION_COUTURE', 'Confection couture', 'roman_shades', '🪟', true, true, 300, 'fixed', 'piece', 'Confection couture', false),
('CONFECTION_COUTURE_INCLUANT_GANSE', 'Confection couture incluant ganse', 'curtains', '🪟', true, true, 800, 'fixed', 'piece', 'Confection couture incluant ganse', false),
('CORDE_L_G_REMENT_PLOMB_E', 'Corde légèrement plombée', 'curtains', '🪟', true, true, 0, 'fixed', 'piece', 'Corde légèrement plombée', false),
('CORDE_PIPING', 'Corde Piping', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Corde Piping', false),
('COURBE_CS', 'Courbe CS', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Courbe CS', false),
('COURBE_DS', 'Courbe DS', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Courbe DS', false),
('COURBE_KS', 'Courbe KS', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Courbe KS', false),
('CURSEUR', 'Curseur', 'general', '🔧', false, true, 30, 'fixed', 'piece', 'Curseur', false),
('CURSEUR_FERMETURE_CLAIR', 'Curseur fermeture éclair', 'general', '🔧', false, true, 30, 'fixed', 'piece', 'Curseur fermeture éclair', false),
('DUNE_019', 'Dune 019', 'roman_shades', '🪟', false, true, 175, 'fixed', 'piece', 'Dune 019', false),
('EMBOUT_D_ARRET_ET_CAPUCHON_BLANC', 'Embout d''arret et capuchon blanc', 'curtains', '🪟', false, true, 180, 'fixed', 'piece', 'Embout d''arret et capuchon blanc', false),
('ENTOILAGE_RIDEAUX', 'Entoilage rideaux', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Entoilage rideaux', false),
('FERMETURES_CLAIRS', 'Fermetures éclairs', 'general', '🔧', false, true, 83, 'fixed', 'piece', 'Fermetures éclairs', false),
('FOAM_ASSISE_1_8_1', 'Foam Assise 1.8 - 1''''', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam Assise 1.8 - 1''''', false),
('FOAM_ASSISE_1_8_2', 'Foam Assise 1.8 - 2''''', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam Assise 1.8 - 2''''', false),
('FOAM_ASSISE_1_8_3', 'Foam Assise 1.8 - 3''''', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam Assise 1.8 - 3''''', false),
('FOAM_ASSISE_1_8_4', 'Foam Assise 1.8 - 4''''', 'general', '🔧', false, true, 2000, 'fixed', 'piece', 'Foam Assise 1.8 - 4''''', false),
('FOAM_ASSISE_1_8_5', 'Foam Assise 1.8 - 5''''', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam Assise 1.8 - 5''''', false),
('FOAM_ASSISE_1_8_6', 'Foam Assise 1.8 - 6''''', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam Assise 1.8 - 6''''', false),
('FOAM_DOSSIER_1118', 'Foam Dossier 1118', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam Dossier 1118', false),
('FOAM_EXT_RIEUR_ENNIS', 'Foam extérieur Ennis', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Foam extérieur Ennis', false),
('FRAIS_ADMIN', 'Frais Admin', 'general', '🔧', false, true, 5, 'fixed', 'piece', 'Frais Admin', false),
('FRAIS_ADMIN', 'Frais admin', 'curtains', '🪟', false, true, 10, 'fixed', 'piece', 'Frais admin', false),
('HOUSSE_DOUBLE', 'Housse Double', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Housse Double', false),
('INTIMATE_040_58', 'Intimate 040 - 58''''', 'roman_shades', '🪟', false, true, 100, 'fixed', 'piece', 'Intimate 040 - 58''''', false),
('MAXWELL', 'Maxwell', 'curtains', '🪟', false, true, 1150, 'fixed', 'piece', 'Maxwell', false),
('NIGHTFALL_54', 'Nightfall 54''''', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Nightfall 54''''', false),
('PELON_WAVE', 'Pelon Wave', 'curtains', '🪟', false, true, 170, 'fixed', 'piece', 'Pelon Wave', false),
('POLYESTER_FOAM_KODEL', 'Polyester Foam - KODEL', 'general', '🔧', false, true, 460, 'fixed', 'piece', 'Polyester Foam - KODEL', false),
('PRIX_PAR_STORE', 'Prix par Store', 'roman_shades', '🪟', false, true, 100, 'fixed', 'piece', 'Prix par Store', false),
('PRIX_UNITAIRE', 'Prix unitaire', 'curtains', '🪟', false, true, 10505, 'fixed', 'piece', 'Prix unitaire', false),
('PRIX_UNITAIRE_RETAIL', 'Prix unitaire RETAIL', 'general', '🔧', false, true, 9792, 'fixed', 'piece', 'Prix unitaire RETAIL', false),
('RAIL_DS_BLANCHE', 'Rail DS blanche', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Rail DS blanche', false),
('RAIL_KS_NOIR_GRIS_IVOIRE', 'Rail KS Noir / Gris / Ivoire', 'curtains', '🪟', false, true, 500, 'fixed', 'piece', 'Rail KS Noir / Gris / Ivoire', false),
('RUBAN_RIPPLEFOLD_NOIR_OU_TRANSPARENT', 'Ruban Ripplefold noir ou transparent', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Ruban Ripplefold noir ou transparent', false),
('RUBAN_PRESSION_4_50_RT75_25', 'Ruban à pression 4.50" RT75.25', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Ruban à pression 4.50" RT75.25', false),
('SHIPPING', 'SHIPPING', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'SHIPPING', false),
('SHIPPING', 'Shipping', 'roman_shades', '🪟', false, true, 33, 'fixed', 'piece', 'Shipping', false),
('SUNBRELLA', 'SUNBRELLA', 'general', '🔧', false, true, 556, 'fixed', 'piece', 'SUNBRELLA', false),
('SUPPORT_MURS_BLANC', 'Support Murs Blanc', 'curtains', '🪟', false, true, 300, 'fixed', 'piece', 'Support Murs Blanc', false),
('SUPPORT_PLAFOND_BLANC', 'Support Plafond Blanc', 'curtains', '🪟', false, true, 0, 'fixed', 'piece', 'Support Plafond Blanc', false),
('TEMPS', 'Temps', 'general', '🔧', false, true, 175, 'fixed', 'piece', 'Temps', false),
('TEMPS_FOAM', 'Temps FOAM', 'general', '🔧', false, true, 125, 'fixed', 'piece', 'Temps FOAM', false),
('TISSU_DESSOUS', 'Tissu dessous', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Tissu dessous', false),
('TISSU_PIPING', 'Tissu piping', 'general', '🔧', false, true, 0, 'fixed', 'piece', 'Tissu piping', false),
('LA_VERGE', 'à la verge', 'general', '🔧', false, true, 13, 'fixed', 'piece', 'à la verge', false),
('TIQUETTE', 'Étiquette', 'general', '🔧', false, true, 30, 'fixed', 'piece', 'Étiquette', false)
;

-- Import ALL Services (17 items)
INSERT INTO service (code, name, base_price_cents, category, is_custom, pricing_model, base_unit, min_quantity, description, estimated_hours) VALUES
('AJOUT_D_UN_ENTOILAGE', 'AJOUT D''UN ENTOILAGE', 2750, 'general', false, 'fixed', 'piece', 1, 'AJOUT D''UN ENTOILAGE', 2.0),
('AJOUT_D_UNE_INSERTION', 'AJOUT D''UNE INSERTION', 3500, 'general', false, 'fixed', 'piece', 1, 'AJOUT D''UNE INSERTION', 2.0),
('AVEC_PIPING', 'Avec Piping', 5500, 'general', false, 'fixed', 'piece', 1, 'Avec Piping', 2.0),
('BORD_DE_RIDEAU_54_LARGE', 'BORD DE RIDEAU (54" large)', 1500, 'general', false, 'per_linear_foot', 'linear_foot', 1, 'BORD DE RIDEAU (54" large)', 2.0),
('BOUTONS_RECOUVERT', 'BOUTONS RECOUVERT', 175, 'general', false, 'per_piece', 'piece', 1, 'BOUTONS RECOUVERT', 2.0),
('BRETELLE_CACH_E', 'BRETELLE CACHÉE', 6000, 'general', false, 'fixed', 'piece', 1, 'BRETELLE CACHÉE', 2.0),
('COUSSIN_STANDARD', 'COUSSIN STANDARD', 3000, 'general', false, 'fixed', 'piece', 1, 'COUSSIN STANDARD', 2.0),
('JUPES_DE_LIT_AVEC_PLIS', 'JUPES DE LIT AVEC PLIS', 11000, 'general', false, 'fixed', 'piece', 1, 'JUPES DE LIT AVEC PLIS', 2.0),
('JUPES_DE_LIT_SANS_PLIS', 'JUPES DE LIT SANS PLIS', 8000, 'general', false, 'fixed', 'piece', 1, 'JUPES DE LIT SANS PLIS', 2.0),
('MODIFICATION_DE_PLIS', 'MODIFICATION DE PLIS', 3500, 'general', false, 'fixed', 'piece', 1, 'MODIFICATION DE PLIS', 2.0),
('PASSE_POLE', 'PASSE POLE', 4000, 'general', false, 'fixed', 'piece', 1, 'PASSE POLE', 2.0),
('RIDEAU_AUTRES_PLIS', 'RIDEAU AUTRES PLIS', 11500, 'general', false, 'fixed', 'piece', 1, 'RIDEAU AUTRES PLIS', 2.0),
('STANDARD', 'Standard', 3500, 'general', false, 'fixed', 'piece', 1, 'Standard', 2.0),
('STORE_ROMAIN_PRIX_AU_P_C', 'STORE ROMAIN (prix au P.C.)', 700, 'general', false, 'per_square_foot', 'square_foot', 1, 'STORE ROMAIN (prix au P.C.)', 2.0),
('T_TE_DE_LIT', 'TÊTE DE LIT', 3500, 'general', false, 'fixed', 'piece', 1, 'TÊTE DE LIT', 2.0),
('T_TE_ENTOILAGE', 'TÊTE ENTOILAGE', 4500, 'general', false, 'fixed', 'piece', 1, 'TÊTE ENTOILAGE', 2.0),
('VOILAGE_54_LARGE', 'VOILAGE (54" large)', 4000, 'general', false, 'per_linear_foot', 'linear_foot', 1, 'VOILAGE (54" large)', 2.0)
;

-- Import ALL Materials (26 items)
INSERT INTO material (name, price_cents, category, is_active) VALUES
('Aurore 110''''', 1600, 'undefined', true),
('Blackout Dim-Out 110"', 4350, 'undefined', true),
('Blackout Dim-Out 54" Blanc', 2100, 'undefined', true),
('Blackout Dim-Out 54" Noir', 2800, 'undefined', true),
('Blackout Nightfall 110"', 3450, 'undefined', true),
('Blackout Nightfall 54"', 2500, 'undefined', true),
('Blackout Nightfall 54" Beige', 1750, 'undefined', true),
('Cordura Denier 500', 1600, 'undefined', true),
('Coton', 50, 'undefined', true),
('Coton blanc 45''''', 850, 'undefined', true),
('Cuirette', 150, 'undefined', true),
('Dim-Out', 100, 'undefined', true),
('Doublure Aurore 110"', 1550, 'undefined', true),
('Doublure nylon imperméable', 950, 'undefined', true),
('Hydro Fend 60''''', 3500, 'undefined', true),
('Kodel', 460, 'undefined', true),
('Morceau de tissu pour réparation (exemple Cordura)', 500, 'undefined', true),
('Phifertex (rouleau en stock)', 3000, 'undefined', true),
('Rembourrage', 150, 'undefined', true),
('Saletex Chardonnay (avec fil de plomb) 118"', 3000, 'undefined', true),
('Sunbrella', 250, 'undefined', true),
('Sunbrella (rouleau en stock)', 3000, 'undefined', true),
('Tissu Adrien 100% coton', 1200, 'undefined', true),
('Typar', 125, 'undefined', true),
('Velours', 150, 'undefined', true),
('Voilage', 100, 'undefined', true)
;

-- Import ALL Accessories (101 items)
INSERT INTO accessory (name, price_cents, category, is_active) VALUES
('Aiguilles à machine', 699, 'undefined', true),
('ALENDEL - AM-BI-ENCE 1-3/8" - RIPPLEFOLD', 0, 'undefined', true),
('ALENDEL - BAYVIEW 1-1/8" - PLAIN', 430, 'undefined', true),
('ALTRO DESIGN - CRS 1-1/8''''', 0, 'undefined', true),
('ALTRO DESIGN - PRIMA 2-1/4', 0, 'undefined', true),
('ALTRO DESIGN - RAIL DS', 0, 'undefined', true),
('ALTRO DESIGN - RAIL RKS - Recessed', 1500, 'undefined', true),
('Bande élastique 1po', 295, 'undefined', true),
('Biais', 120, 'undefined', true),
('Biais Sunbrella', 400, 'undefined', true),
('Boite de craie', 1135, 'undefined', true),
('Bracket 2-1/4'''' à 5-1/8" Ajustable', 0, 'undefined', true),
('Bracket ajustable', 0, 'undefined', true),
('Bâton fibre 30" Clear', 0, 'undefined', true),
('Bâton fibre 36" Blanc', 0, 'undefined', true),
('Bâton fibre 48" Blanc', 0, 'undefined', true),
('Bâton fibre 48" Clear', 0, 'undefined', true),
('Bâton fibre 60" Blanc', 0, 'undefined', true),
('Bâton fibre 96'''' Blanc', 0, 'undefined', true),
('Bâton transparent 30"', 0, 'undefined', true),
('Chariot Crochets', 200, 'undefined', true),
('Chariot Maitre', 0, 'undefined', true),
('Chariot Ripplefold Blanc 60%', 80, 'undefined', true),
('Chariot Ripplefold Blanc 80%', 0, 'undefined', true),
('Corde plombée', 60, 'undefined', true),
('Corde à capuchon', 60, 'undefined', true),
('Corde à piping', 35, 'undefined', true),
('Corde à piping 1/2', 225, 'undefined', true),
('Corde à piping 5/16', 100, 'undefined', true),
('Cordon élastique (rond) blanc ou noir', 115, 'undefined', true),
('Courroie nylon 1po', 75, 'undefined', true),
('Courroie polypropylène 1.5po (Webbing)', 195, 'undefined', true),
('Courroie polypropylène 1po (Webbing)', 145, 'undefined', true),
('Craie', 175, 'undefined', true),
('Crochet rideaux métal 1-3/8"', 15, 'undefined', true),
('Crochets à rideau de type Wave', 25, 'undefined', true),
('Curseur #3 ou #5', 50, 'undefined', true),
('Curseur #7 ou #10', 50, 'undefined', true),
('Description', 10, 'undefined', true),
('Embout d''arret et capuchon blanc', 0, 'undefined', true),
('Embout décoratif (pair)', 0, 'undefined', true),
('Fabric Gard Canette', 3000, 'undefined', true),
('Fabric Gard Spray', 6000, 'undefined', true),
('Fil Tex 60 (Bobine 3750v)', 1200, 'undefined', true),
('Fil à surjeter Bobine 150m (meuble à l''avant)', 300, 'undefined', true),
('Fil à surjeteuse Tex 27 (Bobine 6000v)', 600, 'undefined', true),
('Fil élastique - Bobine 1000m', 800, 'undefined', true),
('Fils à jeans Tex80 - Bobine 200m', 700, 'undefined', true),
('Frais admin', 0, 'undefined', true),
('Frais admin KLAUDE', 10, 'undefined', true),
('Galon croisé 3/4po', 109, 'undefined', true),
('Master carriers Start (3 snaps)', 0, 'undefined', true),
('mètre', 160, 'undefined', true),
('Patch à genoux 4'''' x 6''''', 475, 'undefined', true),
('Pelon 4po', 75, 'undefined', true),
('Pelon 6po', 90, 'undefined', true),
('Prix unitaire', 100, 'undefined', true),
('Rail 1-1/8'''' Ripplefold 10 pieds', 0, 'undefined', true),
('Rail 1-1/8'''' Ripplefold 12 pieds', 0, 'undefined', true),
('Rail 1-1/8'''' Ripplefold 16 pieds', 0, 'undefined', true),
('Rail 1-1/8'''' Ripplefold 6 pieds', 0, 'undefined', true),
('Rail 1-1/8'''' Ripplefold 8 pieds', 0, 'undefined', true),
('Rail 1-3/8'''' Ripplefold', 0, 'undefined', true),
('Rail CRS 28mm Blanc', 0, 'undefined', true),
('Rail CRS 28mm Inox/Gold/Blanc/Taupe/Bronze/Graphite', 0, 'undefined', true),
('Rail CRS 28mm Noir / Gris / Or / Bronze', 0, 'undefined', true),
('Rail DS blanche', 450, 'undefined', true),
('Rail KS Noir / Gris / Ivoire', 0, 'undefined', true),
('RAIL MEDICTRACK', 550, 'undefined', true),
('RAIL RKS - Recessed noir', 0, 'undefined', true),
('Ruban ripplefold blanc', 300, 'undefined', true),
('Ruban ripplefold transparent', 400, 'undefined', true),
('Shipping', 0, 'undefined', true),
('Snap antique Brass (2 parties)', 75, 'undefined', true),
('Support Murs 3-1/2''''', 0, 'undefined', true),
('Support Murs 3-1/2'''' (Rond chic))', 0, 'undefined', true),
('Support Murs Blanc', 0, 'undefined', true),
('Support Plafond Blanc', 100, 'undefined', true),
('Support Suspension 12''''', 0, 'undefined', true),
('Support Suspension 24''''', 0, 'undefined', true),
('Support Suspension 36''''', 0, 'undefined', true),
('Support Suspension 48''''', 0, 'undefined', true),
('Support Suspension 60''''', 0, 'undefined', true),
('Support Suspension 72''''', 0, 'undefined', true),
('Tringle lisse 144''''', 0, 'undefined', true),
('Tête de rideau de type entoilage multifonction', 200, 'undefined', true),
('Tête de rideau de type entoilage multifonction (2,5v)', 175, 'undefined', true),
('Velcros 1-1/2"', 118, 'undefined', true),
('Velcros autocollant 1" (mâle ou femelle)', 290, 'undefined', true),
('Velcros autocollant 1-1/2" (mâle ou femelle)', 400, 'undefined', true),
('Velcros autocollant 2" (mâle ou femelle)', 550, 'undefined', true),
('Velcros à coudre 1" (mâle ou femelle)', 140, 'undefined', true),
('Velcros à coudre 1-1/2" (mâle ou femelle)', 225, 'undefined', true),
('Velcros à coudre 2" (mâle ou femelle)', 275, 'undefined', true),
('Élastique 4mm blanc', 75, 'undefined', true),
('Élastique 6mm blanc ou noir', 100, 'undefined', true),
('Élastique Bretelle 1-1/2''''', 370, 'undefined', true),
('Élastique tricoté 1''''', 75, 'undefined', true),
('Élastique tricoté 1-1/2''''', 125, 'undefined', true),
('Élastique tricoté 1-1/4''''', 85, 'undefined', true),
('Élastique tricoté 2''''', 150, 'undefined', true)
;

-- Success message
DO $$
BEGIN
    RAISE NOTICE '🎉 ALL CUSTOMER DATA IMPORTED SUCCESSFULLY!';
    RAISE NOTICE '📊 Garment Types: % items', (SELECT COUNT(*) FROM garment_type);
    RAISE NOTICE '📊 Services: % items', (SELECT COUNT(*) FROM service);
    RAISE NOTICE '📊 Materials: % items', (SELECT COUNT(*) FROM material);
    RAISE NOTICE '📊 Accessories: % items', (SELECT COUNT(*) FROM accessory);
    RAISE NOTICE '✅ Ready to test the intake form!';
END $$;
